<?php declare(strict_types=1);

namespace PHPCraftdream\Garnet\Kernel\Io\GarnetCli;

/**
 * Rewrite public asset paths from the app-name form used at build time
 * (/assets/MyApp/, /upload/MyApp/) to the deployed public-name form
 * (/assets/myapp/, /upload/myapp/).
 *
 * Shared between `bundle` (in-place on the dist tree) and `deploy:diff`
 * (shadow-temp copies so local dev files stay untouched).
 */
final class PublicPathRebrander {
    /**
     * Returns strtr-style pairs: ['from' => 'to', ...].
     *
     * Covers both original-case and lowercase variants so the rewrite is
     * idempotent when the same content passes through twice.
     *
     * @return array<string, string>
     */
    public static function rewritePairs(string $appName, string $publicName): array {
        return [
            "/assets/{$appName}/" => "/assets/{$publicName}/",
            "/upload/{$appName}/" => "/upload/{$publicName}/",
            '/assets/' . strtolower($appName) . '/' => "/assets/{$publicName}/",
            '/upload/' . strtolower($appName) . '/' => "/upload/{$publicName}/",
        ];
    }

    /**
     * Apply the rewrite pairs to a string. Idempotent: running it on
     * already-rebranded content is a no-op (the 'from' patterns won't match).
     */
    public static function rewriteContent(string $content, array $pairs): string {
        return str_replace(array_keys($pairs), array_values($pairs), $content);
    }

    /**
     * Content of the per-app index.php shim that bundle produces.
     * Boots via <runtime-dir>/_shared_index.php (sibling of the per-app
     * dir on the host).
     */
    public static function perAppIndexContent(string $runtimeDirName): string {
        return "<?php\nrequire __DIR__ . '/../" . $runtimeDirName . "/_shared_index.php';\n";
    }

    /**
     * Absolute filesystem paths of the four *Gen.php files that carry
     * asset URLs and must be re-shipped after every frontend rebuild.
     *
     * Two live under the app (gitignored, regenerated by rspack):
     *   <appDir>/Foreground/Foreground{Js,Css}Gen.php
     * Two live under the framework (gitignored, regenerated by rspack):
     *   <frameworkDir>/Bundle/Framework{Js,Css}Gen.php
     *
     * Dual-mode: the app dir comes from GarnetEnv (GARNET_APP_DIR in app-mode,
     * GARNET_ROOT/Apps/<name> in the legacy monorepo) and the framework dir
     * from GarnetRunner — never from GARNET_ROOT directly, which in app-mode is
     * the framework package, not the app.
     *
     * @return list<string>
     */
    public static function genFiles(string $appName): array {
        $appDir = GarnetEnv::getAppDir($appName);
        $frameworkBundle = GarnetRunner::$frameworkDir . DS . 'Bundle';

        return [
            $appDir . DS . 'Foreground' . DS . 'ForegroundJsGen.php',
            $appDir . DS . 'Foreground' . DS . 'ForegroundCssGen.php',
            $frameworkBundle . DS . 'FrameworkJsGen.php',
            $frameworkBundle . DS . 'FrameworkCssGen.php',
        ];
    }
}
