<?php declare(strict_types=1);

namespace PHPCraftdream\Garnet\Kernel\Io\FileUpload {
    use PHPCraftdream\Garnet\Kernel\Io\Router\ControllerTools;
    use PHPCraftdream\Garnet\Kernel\Io\Router\Mime;
    use Psr\Http\Message\ResponseInterface;

    /**
     * Secure file serving from non-public directories.
     *
     * Framework-level — provides file delivery with:
     * - Path traversal protection
     * - Access control via callable checker
     * - Proper Content-Type and Content-Disposition headers
     * - Optional inline (images) vs attachment (downloads) mode
     *
     * Usage:
     *   return SecureFileServing::serve(
     *       uploadDir:   $app->uploadDir,
     *       subDir:      'support',
     *       storedName:  $attachment['stored_name'],
     *       displayName: $attachment['original_name'],
     *       accessCheck: fn() => $ticket['account_id'] === $userId || $isModerator,
     *   );
     */
    class SecureFileServing {
        /**
         * Serve a file from a protected directory.
         *
         * @param string   $uploadDir    Base upload directory (BaseAppInit::uploadDir)
         * @param string   $subDir       Module subdirectory
         * @param string   $storedName   Filename on disk (generated by FileUploadManager)
         * @param string   $displayName  Original filename shown to the user
         * @param callable $accessCheck  fn(): bool — return true if current user can access this file
         * @param bool     $inline       True for inline display (images), false for download attachment
         * @return ResponseInterface
         */
        public static function serve(
            string $uploadDir,
            string $subDir,
            string $storedName,
            string $displayName,
            callable $accessCheck,
            bool $inline = true,
        ): ResponseInterface {
            // Access control
            if (!$accessCheck()) {
                return ControllerTools::JSON(['error' => 'Access denied'], status: 403);
            }

            // Path traversal protection — strip any directory components
            $safeName = basename($storedName);
            $basePath = rtrim($uploadDir, '/\\') . DIRECTORY_SEPARATOR;

            if ($subDir !== '') {
                $basePath .= trim($subDir, '/\\') . DIRECTORY_SEPARATOR;
            }
            $fullPath = $basePath . $safeName;

            // Resolve real path and verify it's within base directory
            $realPath = realpath($fullPath);
            $realBase = realpath($basePath);

            if ($realPath === false || $realBase === false || !str_starts_with($realPath, $realBase)) {
                return ControllerTools::JSON(['error' => 'File not found'], status: 404);
            }

            if (!is_file($realPath)) {
                return ControllerTools::JSON(['error' => 'File not found'], status: 404);
            }

            // Read file
            $content = file_get_contents($realPath);

            if ($content === false) {
                return ControllerTools::JSON(['error' => 'Failed to read file'], status: 500);
            }

            // Build response
            $mime = Mime::getFileMime($displayName) ?? 'application/octet-stream';
            $disposition = $inline && self::isInlineSafe($mime)
                ? 'inline'
                : 'attachment; filename="' . self::sanitizeFilename($displayName) . '"';

            $response = ControllerTools::ok('');
            $response = $response
                ->withHeader('Content-Type', $mime)
                ->withHeader('Content-Disposition', $disposition)
                ->withHeader('Content-Length', (string)strlen($content))
                ->withHeader('Cache-Control', 'private, max-age=3600');

            $response->getBody()->write($content);

            return $response;
        }

        /**
         * Check if MIME type is safe to display inline (not executable).
         */
        protected static function isInlineSafe(string $mime): bool {
            return str_starts_with($mime, 'image/')
                || $mime === 'application/pdf'
                || str_starts_with($mime, 'text/');
        }

        /**
         * Sanitize filename for Content-Disposition header.
         */
        protected static function sanitizeFilename(string $name): string {
            // Remove anything that isn't a word char, dot, dash, space, or common Unicode
            $safe = preg_replace('/[^\w.\- \p{L}]/u', '_', $name);

            return $safe ?: 'download';
        }
    }
}
