<?php declare(strict_types=1);

namespace PHPCraftdream\Garnet\Kernel\Io\FileUpload {
    use GuzzleHttp\Psr7\Utils;
    use PHPCraftdream\Garnet\Kernel\Io\Router\ControllerTools;
    use Psr\Http\Message\ResponseInterface;

    /**
     * Secure file serving from non-public directories.
     *
     * Framework-level — provides file delivery with:
     * - Path traversal protection
     * - Access control via callable checker
     * - Proper Content-Type and Content-Disposition headers
     * - Optional inline (images) vs attachment (downloads) mode
     *
     * Usage:
     *   return SecureFileServing::serve(
     *       uploadDir:   $app->uploadDir,
     *       subDir:      'support',
     *       storedName:  $attachment['stored_name'],
     *       displayName: $attachment['original_name'],
     *       mimeType:    $attachment['mime_type'],
     *       accessCheck: fn() => $ticket['account_id'] === $userId || $isModerator,
     *   );
     */
    class SecureFileServing {
        /**
         * Serve a file from a protected directory.
         *
         * @param string   $uploadDir    Base upload directory (BaseAppInit::uploadDir)
         * @param string   $subDir       Module subdirectory
         * @param string   $storedName   Filename on disk (generated by FileUploadManager)
         * @param string   $displayName  Original filename shown to the user
         * @param string   $mimeType     Validated MIME type from the stored upload record
         *                               (never re-derived from the user-supplied display name)
         * @param callable $accessCheck  fn(): bool — return true if current user can access this file
         * @param bool     $inline       True for inline display (images), false for download attachment
         * @return ResponseInterface
         */
        public static function serve(
            string $uploadDir,
            string $subDir,
            string $storedName,
            string $displayName,
            string $mimeType,
            callable $accessCheck,
            bool $inline = true,
        ): ResponseInterface {
            // Access control
            if (!$accessCheck()) {
                return ControllerTools::JSON(['error' => 'Access denied'], status: 403);
            }

            // Path traversal protection — reject any directory traversal in subDir
            if (!self::isSafeSubDir($subDir)) {
                return ControllerTools::JSON(['error' => 'File not found'], status: 404);
            }

            // Path traversal protection — strip any directory components
            $safeName = basename($storedName);
            $basePath = rtrim($uploadDir, '/\\') . DIRECTORY_SEPARATOR;

            if ($subDir !== '') {
                $basePath .= trim($subDir, '/\\') . DIRECTORY_SEPARATOR;
            }
            $fullPath = $basePath . $safeName;

            // Resolve real path and verify it's within base directory
            $realPath = realpath($fullPath);
            $realBase = realpath($basePath);

            if ($realPath === false || $realBase === false || !str_starts_with($realPath, $realBase)) {
                return ControllerTools::JSON(['error' => 'File not found'], status: 404);
            }

            if (!is_file($realPath)) {
                return ControllerTools::JSON(['error' => 'File not found'], status: 404);
            }

            $size = filesize($realPath);

            if ($size === false) {
                return ControllerTools::JSON(['error' => 'Failed to read file'], status: 500);
            }

            // Build response — MIME comes from the validated stored record, never from
            // the user-controlled display filename, and SVG/HTML are never inline-safe.
            $disposition = $inline && self::isInlineSafe($mimeType)
                ? 'inline'
                : 'attachment; filename="' . self::sanitizeFilename($displayName) . '"';

            $response = ControllerTools::ok('');
            $response = $response
                ->withHeader('Content-Type', $mimeType)
                ->withHeader('Content-Disposition', $disposition)
                ->withHeader('Content-Length', (string)$size)
                ->withHeader('Cache-Control', 'private, max-age=3600')
                ->withHeader('X-Content-Type-Options', 'nosniff');

            $handle = fopen($realPath, 'rb');

            if ($handle === false) {
                return ControllerTools::JSON(['error' => 'Failed to read file'], status: 500);
            }

            // Stream the file from disk instead of buffering it into a PHP string —
            // avoids holding the whole (potentially tens-of-MB) file in memory.
            $response = $response->withBody(Utils::streamFor($handle));

            return $response;
        }

        /**
         * Reject subdirectory paths containing traversal or null-byte sequences.
         */
        protected static function isSafeSubDir(string $subDir): bool {
            if ($subDir === '') {
                return true;
            }

            if (str_contains($subDir, "\0")) {
                return false;
            }

            $normalized = str_replace('\\', '/', $subDir);
            $segments = explode('/', $normalized);

            foreach ($segments as $segment) {
                if ($segment === '..') {
                    return false;
                }
            }

            return true;
        }

        /**
         * Check if MIME type is safe to display inline (not executable).
         *
         * SVG and HTML/XML are deliberately excluded even though browsers treat
         * them as "safe" media types — both can carry active script content and
         * must never be inline-rendered from the app's own origin.
         */
        protected static function isInlineSafe(string $mime): bool {
            if ($mime === 'image/svg+xml' || $mime === 'text/html' || $mime === 'text/xml' || $mime === 'application/xhtml+xml') {
                return false;
            }

            return str_starts_with($mime, 'image/')
                || $mime === 'application/pdf'
                || str_starts_with($mime, 'text/');
        }

        /**
         * Sanitize filename for Content-Disposition header.
         */
        protected static function sanitizeFilename(string $name): string {
            // Remove anything that isn't a word char, dot, dash, space, or common Unicode
            $safe = preg_replace('/[^\w.\- \p{L}]/u', '_', $name);

            return $safe ?: 'download';
        }
    }
}
