<?php declare(strict_types=1);

use PHPCraftdream\Garnet\Bundle\FrameworkJsGen;

/**
 * FrameworkJsGen is regenerated by rspack on every front-end build, so the
 * hashes inside paths change every time. Test the SHAPE of the URLs (prefix,
 * directory, extension, hash format), never the exact hash.
 */
describe('FrameworkJsGen', function (): void {
    $methods = ['auth', 'framework', 'gridtable', 'yandextarget'];

    describe('Path format', function () use ($methods): void {
        it('all paths start with /assets/framework/', function () use ($methods): void {
            foreach ($methods as $m) {
                expect(FrameworkJsGen::$m())->toMatch('#^/assets/framework/#');
            }
        });

        it('all paths contain gen/js directory', function () use ($methods): void {
            foreach ($methods as $m) {
                expect(FrameworkJsGen::$m())->toMatch('#/gen/js/#');
            }
        });

        it('all paths end with .gen.js', function () use ($methods): void {
            foreach ($methods as $m) {
                expect(FrameworkJsGen::$m())->toMatch('#\.gen\.js$#');
            }
        });

        it('all paths contain hash for cache busting', function () use ($methods): void {
            foreach ($methods as $m) {
                expect(FrameworkJsGen::$m())->toMatch('/\.[a-f0-9]+\.gen\.js$/');
            }
        });
    });
});
