<?php declare(strict_types=1);

use PHPCraftdream\Garnet\Bundle\FrameworkCssGen;

/**
 * FrameworkCssGen is regenerated by rspack on every front-end build, so the
 * hashes inside paths change every time. Test the SHAPE of the URLs (prefix,
 * directory, extension), never the exact hash.
 */
describe('FrameworkCssGen', function (): void {
    describe('framework()', function (): void {
        // FrameworkCssGen only exists once a real frontend build has run
        // (php garnet build/prepare) — the framework's own CI jobs that run
        // kahlan (kernel-tests/bundle-tests) deliberately never build the
        // frontend, so skip gracefully instead of failing with "class not
        // found" when it isn't there.
        beforeEach(function (): void {
            skipIf(!class_exists(FrameworkCssGen::class));
        });

        it('path starts with /assets/framework/', function (): void {
            expect(FrameworkCssGen::framework())->toMatch('#^/assets/framework/#');
        });

        it('path ends with .css', function (): void {
            expect(FrameworkCssGen::framework())->toMatch('#\.css$#');
        });

        it('path contains gen/css directory', function (): void {
            expect(FrameworkCssGen::framework())->toMatch('#/gen/css/#');
        });

        it('returns string', function (): void {
            expect(is_string(FrameworkCssGen::framework()))->toBe(true);
        });
    });
});
