export enum EPhase {
    INPUT_EMAIL = 'INPUT_EMAIL',
    INPUT_EMAIL_AFTER_TIMEOUT = 'INPUT_EMAIL_AFTER_TIMEOUT',
    INPUT_EMAIL_AFTER_FAIL_TRIES = 'INPUT_EMAIL_AFTER_FAIL_TRIES',
    INPUT_EMAIL_WRONG_VALUE = 'INPUT_EMAIL_WRONG_VALUE',
    INPUT_EMAIL_REQUEST_ERROR = 'INPUT_EMAIL_REQUEST_ERROR',
    INPUT_CODE = 'INPUT_CODE',
    INPUT_CODE_FAIL = 'INPUT_CODE_FAIL',
    INPUT_CODE_WRONG_VALUE = 'INPUT_CODE_WRONG_VALUE',
    INPUT_CODE_REQUEST_ERROR = 'INPUT_CODE_REQUEST_ERROR',
}
